from ._test0 import add as add0
from ._test1 import add as add1
from ._test2 import add as add2
from ._test3 import add as add3
from ._test4 import add as add4
from ._test5 import add as add5
from ._test6 import add as add6
from ._test7 import add as add7
from ._test8 import add as add8
from ._test9 import add as add9
from ._test10 import add as add10
from ._test11 import add as add11
from ._test12 import add as add12
from ._test13 import add as add13
from ._test14 import add as add14
from ._test15 import add as add15
from ._test16 import add as add16
from ._test17 import add as add17
from ._test18 import add as add18
from ._test19 import add as add19
from ._test20 import add as add20
from ._test21 import add as add21
from ._test22 import add as add22
from ._test23 import add as add23
from ._test24 import add as add24
from ._test25 import add as add25
from ._test26 import add as add26
from ._test27 import add as add27
from ._test28 import add as add28
from ._test29 import add as add29
from ._test30 import add as add30
from ._test31 import add as add31
from ._test32 import add as add32
from ._test33 import add as add33
from ._test34 import add as add34
from ._test35 import add as add35
from ._test36 import add as add36
from ._test37 import add as add37
from ._test38 import add as add38
from ._test39 import add as add39
from ._test40 import add as add40
from ._test41 import add as add41
from ._test42 import add as add42
from ._test43 import add as add43
from ._test44 import add as add44
from ._test45 import add as add45
from ._test46 import add as add46
from ._test47 import add as add47
from ._test48 import add as add48
from ._test49 import add as add49


from ._test0 import subtract as subtract0
from ._test1 import subtract as subtract1
from ._test2 import subtract as subtract2
from ._test3 import subtract as subtract3
from ._test4 import subtract as subtract4
from ._test5 import subtract as subtract5
from ._test6 import subtract as subtract6
from ._test7 import subtract as subtract7
from ._test8 import subtract as subtract8
from ._test9 import subtract as subtract9
from ._test10 import subtract as subtract10
from ._test11 import subtract as subtract11
from ._test12 import subtract as subtract12
from ._test13 import subtract as subtract13
from ._test14 import subtract as subtract14
from ._test15 import subtract as subtract15
from ._test16 import subtract as subtract16
from ._test17 import subtract as subtract17
from ._test18 import subtract as subtract18
from ._test19 import subtract as subtract19
from ._test20 import subtract as subtract20
from ._test21 import subtract as subtract21
from ._test22 import subtract as subtract22
from ._test23 import subtract as subtract23
from ._test24 import subtract as subtract24
from ._test25 import subtract as subtract25
from ._test26 import subtract as subtract26
from ._test27 import subtract as subtract27
from ._test28 import subtract as subtract28
from ._test29 import subtract as subtract29
from ._test30 import subtract as subtract30
from ._test31 import subtract as subtract31
from ._test32 import subtract as subtract32
from ._test33 import subtract as subtract33
from ._test34 import subtract as subtract34
from ._test35 import subtract as subtract35
from ._test36 import subtract as subtract36
from ._test37 import subtract as subtract37
from ._test38 import subtract as subtract38
from ._test39 import subtract as subtract39
from ._test40 import subtract as subtract40
from ._test41 import subtract as subtract41
from ._test42 import subtract as subtract42
from ._test43 import subtract as subtract43
from ._test44 import subtract as subtract44
from ._test45 import subtract as subtract45
from ._test46 import subtract as subtract46
from ._test47 import subtract as subtract47
from ._test48 import subtract as subtract48
from ._test49 import subtract as subtract49
